// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/device": {
            "get": {
                "description": "Returns a list of all active instances with ID, name, and status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "List devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.InstanceInfo"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Generates a new device ID (hashed) and initializes a WhatsApp client session",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Create a new device",
                "parameters": [
                    {
                        "description": "Device Name",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.CreateDeviceResponse"
                        }
                    }
                }
            }
        },
        "/device/{id}/rename": {
            "put": {
                "description": "Updates the display name of an existing device/instance",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Rename a device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Device Name",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RenameDeviceResponse"
                        }
                    }
                }
            }
        },
        "/device/{id}/qr": {
            "get": {
                "description": "Opens a Server-Sent Events (SSE) stream that pushes QR code data for pairing the WhatsApp session",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Get QR code stream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream with QR code data"
                    }
                }
            }
        },
        "/device/{id}/status": {
            "get": {
                "description": "Returns the connection status (connected/disconnected) of the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Get device status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StatusResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found"
                    }
                }
            }
        },
        "/message/send": {
            "post": {
                "description": "Enqueues a plain text message to be sent asynchronously via RabbitMQ. Supports both 'phone' and 'number' as well as 'message' and 'text' aliases.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "Send a text message",
                "parameters": [
                    {
                        "description": "Text Message Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message queued",
                        "schema": {
                            "$ref": "#/definitions/api.QueuedResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body"
                    },
                    "500": {
                        "description": "Failed to enqueue message"
                    }
                }
            }
        },
        "/message/media": {
            "post": {
                "description": "Enqueues a media message (image, video, document, audio). Downloads the media from `media_url` and uploads it to WhatsApp. Mimetype is optional but recommended for documents/audio.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "Send a media message",
                "parameters": [
                    {
                        "description": "Media Message Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SendMediaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message queued",
                        "schema": {
                            "$ref": "#/definitions/api.QueuedResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body"
                    },
                    "500": {
                        "description": "Failed to enqueue message"
                    }
                }
            }
        },
        "/message/interactive/button": {
            "post": {
                "description": "Enqueues an interactive button message to be sent asynchronously via RabbitMQ. The message uses WhatsApp NativeFlowMessage for rendering clickable buttons on the recipient's phone. Supports both 'phone' and 'number' field aliases.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "message"
                ],
                "summary": "Send interactive buttons",
                "parameters": [
                    {
                        "description": "Interactive Button Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message queued",
                        "schema": {
                            "$ref": "#/definitions/api.QueuedResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body"
                    },
                    "500": {
                        "description": "Failed to enqueue message"
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateDeviceRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "Display name for the instance",
                    "example": "Vendas Principal"
                }
            }
        },
        "api.CreateDeviceResponse": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "example": "2a7f8a3e-343f-4d8b-ad3c-ab375af2dfda"
                },
                "name": {
                    "type": "string",
                    "example": "Vendas Principal"
                }
            }
        },
        "api.RenameDeviceResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "device_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "enum": ["connected", "disconnected"],
                    "example": "connected"
                }
            }
        },
        "api.QueuedResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "queued"
                }
            }
        },
        "api.InstanceInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "description": "Hashed device ID"
                },
                "name": {
                    "type": "string",
                    "description": "Display name"
                },
                "connected": {
                    "type": "boolean"
                }
            }
        },
        "api.SendMessageRequest": {
            "type": "object",
            "required": ["device_id"],
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "ID of the connected device to send from",
                    "example": "2a7f8a3e-343f-4d8b-ad3c-ab375af2dfda"
                },
                "number": {
                    "type": "string",
                    "description": "Recipient phone number (DDI+DDD+number, no + sign). Alias: 'phone'",
                    "example": "554399284670"
                },
                "message": {
                    "type": "string",
                    "description": "Body text of the message. Alias: 'text'",
                    "example": "Escolha uma opcao:"
                },
                "title": {
                    "type": "string",
                    "description": "Header title displayed above the message body",
                    "example": "Menu Principal"
                },
                "footer": {
                    "type": "string",
                    "description": "Footer text displayed below the buttons. Alias: 'footerText'",
                    "example": "Powered by Basileia"
                },
                "type": {
                    "type": "string",
                    "description": "Message type: 'button' for interactive buttons",
                    "enum": ["button", "list", ""],
                    "example": "button"
                },
                "buttons": {
                    "type": "array",
                    "description": "Array of button labels (max 3). Use 'Label|custom_id' for custom IDs. Alias: 'choices'",
                    "items": {
                        "type": "string"
                    },
                    "example": ["Sim", "Nao", "Talvez"]
                }
            }
        },
        "api.SendMediaRequest": {
            "type": "object",
            "required": ["device_id", "type"],
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "ID of the connected device to send from",
                    "example": "2a7f8a3e-343f-4d8b-ad3c-ab375af2dfda"
                },
                "number": {
                    "type": "string",
                    "description": "Recipient phone number (DDI+DDD+number, no + sign). Alias: 'phone'",
                    "example": "554399284670"
                },
                "media_url": {
                    "type": "string",
                    "description": "Public URL where the media can be downloaded from. Required if base64 is empty.",
                    "example": "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"
                },
                "base64": {
                    "type": "string",
                    "description": "Base64 encoded media string (e.g. data:image/png;base64,iVBORw0KGgo...). Required if media_url is empty.",
                    "example": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="
                },
                "type": {
                    "type": "string",
                    "description": "Type of media being sent",
                    "enum": ["image", "video", "document", "audio"],
                    "example": "document"
                },
                "caption": {
                    "type": "string",
                    "description": "Caption text attached to the media (images/videos/documents). Alias: 'text'",
                    "example": "Segue anexo o documento solicitado"
                },
                "mimetype": {
                    "type": "string",
                    "description": "Optional custom mimetype (e.g. application/pdf)",
                    "example": "application/pdf"
                },
                "fileName": {
                    "type": "string",
                    "description": "Optional explicit file name when type=document",
                    "example": "relatorio.pdf"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3179",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "WhatsMeow Basileia API",
	Description:      "API WhatsApp multi-device com mensageria assíncrona (RabbitMQ), botões interativos (NativeFlowMessage), e webhooks configuráveis.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
